app:
  port: 8080
  debug: true
  log_level: debug
  secret_key: testsecret
  env: local

# 添加日志配置
log:
  filename: "logs/app.log"
  max_size: 100    # 日志文件最大 100MB
  max_backups: 10  # 最多保留 10 个备份文件
  max_age: 30      # 文件最多保存 30 天
  compress: true   # 压缩旧文件